encoding: UTF-8

permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: kramdown

kramdown:
  input: GFM

highlighter: rouge


# 作者信息
author: 
  name: 黄嘉乐
  email: lecoder@qq.com
  link: http://leleyy1997.github.io/
  weibo:
  github: https://github.com/leleyy1997
  github_username:  leleyy1997
  weibo_username:  leleyy1997

# 站点信息
title : legege's Home
description: 代码源于生活
url: http://leleyy1997.github.io/
rss_url: /feed.xml

# gavatar头像及Favicon
gavatar : /assets/img/lbxx.jpg
favicon : /assets/img/favicon.png

# disqus 设置
#disqus:
#  shortname: blademastercoder

#profile 个人信息

profile_desc : <br>Java Developer<br>

# 首页除了最新文章外显示分类
cates: 
- Essay

# 中文本地化
locals: 
   newest : 最新文章